# Numpy

In [1]:
import numpy as np

## Example 1. Access individual elements of 1-D array

In [5]:
x = np.array([1, 2, 3, 4, 5])
print(x)

print("\n1st element:", x[0])
print("1st element again:", x[-5])
print("2nd element:", x[1])
print("2nd element again:", x[-4])
print("5th element:", x[4])
print("5th element again:", x[-1])

[1 2 3 4 5]

1st element: 1
1st element again: 1
2nd element: 2
2nd element again: 2
5th element: 5
5th element again: 5


## Example 2. Modify an element of 2-D array

In [16]:
print('Original')
x = np.arange(1, 10).reshape(3, 3)
print(x)
print('\n')

print('Element at (0, 0):', x[0, 0])
print('Element at (0, 1):', x[0, 1])
print('Element at (2, 2):', x[2, 2])

print('\n')

# Changing the element in the position (0, 0)
print('Modified')
x[0, 0] = 20
print(x)

Original
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Element at (0, 0): 1
Element at (0, 1): 2
Element at (2, 2): 9


Modified
[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


## Example 3. Delete elements

In [19]:
print('Before deletion: ', end='')
x = np.array([0, 1, 2, 3, 4, 5])
print(x)

# Deletes the informed positions
print('After deletion: ', end='')
x = np.delete(x, [0, 4])
print(x)

Before deletion: [0 1 2 3 4 5]
After deletion: [1 2 3 5]


In [20]:
Y =  np.arange(1, 10).reshape(3, 3)
print(Y)

W = np.delete(Y, 0, axis=0)
print('\n', W)

V = np.delete(Y, [0, 2], axis=1)
print('\n', V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[4 5 6]
 [7 8 9]]

 [[2]
 [5]
 [8]]


## Example 6. Append elements

In [27]:
x = np.array([1, 2, 3, 4, 5])
x = np.append(x, [6, 7, 8])
print(x)

Y = np.arange(1, 10).reshape(3, 3)
print('\n', Y)

W = np.append(Y, [[10, 11, 12]], axis=0)
print('\n', W)

[1 2 3 4 5 6 7 8]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Example 7. Insert elements

In [45]:
x = np.array([1, 2])
x = np.insert(x, 2, [3, 4])
print(x)

Y = np.array([[1, 2, 3], [7, 8, 9]])
print('\n', Y)

W = np.insert(Y, 1, [4, 5 ,6], axis=0)
print('\n', W)

V = np.insert(Y, 1, 5, axis=1)
print('\n', V)

x = np.append(x, [5, 6])
print('\n', x)

[1 2 3 4]

 [[1 2 3]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 5 2 3]
 [7 5 8 9]]
1

 [1 2 3 4 5 6]


## Example 8. Stack arrays

In [52]:
x = np.array([1, 2])
print(x)

Y = np.array([[3, 4], [5, 6]])
print('\n', Y)

z = np.vstack((x, Y))
print('\n', z)

w = np.hstack((Y, x.reshape(2, 1)))
print('\n', w)

[1 2]

 [[3 4]
 [5 6]]

 [[1 2]
 [3 4]
 [5 6]]

 [[3 4 1]
 [5 6 2]]
