# Numpy

In [1]:
import numpy as np

In [51]:
print('Base Array')
x = np.arange(1, 21).reshape(4, 5)
print(x)

Base Array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Example 1. Slicing 

In [56]:
print("Original")
print(x)
print("\nModified")
z = x[1:4, 2:5]
print(z, '\n')
print("OR\n")
y = x[1:, 2:]
print(y)

Original
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Modified
[[ 8  9 10]
 [13 14 15]
 [18 19 20]] 

OR

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [57]:
print("Original")
print(x)

print("\nModified")
# Rank 1 array
z = x[:, 2]
print(z, '\n')

# Rank 2 array
z = x[:, 2:3]
print(z)

Original
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Modified
[ 3  8 13 18] 

[[ 3]
 [ 8]
 [13]
 [18]]


## Example 2. Slicing and editing elements

In [19]:
print("Original")
print(x)

print("\nModified")
z = x[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [22]:
print("Original")
print(z)

print("\nModified")
z[2, 2] = 555
print(z, '\n')

print(x)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]] 

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


## Example 3. Demonstrate the copy() function

In [60]:
print("Original")
X = np.arange(20).reshape(4, 5)
print(X, '\n')

print("Copy of original sliced")
z = X[1:, 2:].copy()
print(z, '\n')

z[2, 2] = 555
print("Modified")
print(z, '\n')

print("Original")
print(X)

Original
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

Copy of original sliced
[[ 7  8  9]
 [12 13 14]
 [17 18 19]] 

Modified
[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]] 

Original
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Example 4 a. Use an array as indices to either make slices, select, or change elements

In [61]:
print("Indices")
indices = np.array([1, 3])
print(indices, '\n')

print("Sliced by indices")
y = X[indices,:]
print(y, '\n')

z = X[:, indices]
print(z)

Indices
[1 3] 

Sliced by indices
[[ 5  6  7  8  9]
 [15 16 17 18 19]] 

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


## Example 5. Demonstrate the diag() function

In [62]:
print("Original")
print(X, '\n')

print("Collected")
z = np.diag(X)
print(z, '\n')

# Elements above the diagonal
print("Above the diagonal")
z = np.diag(X, k=1)
print(z, '\n')

# Elements under the diagonal
print("Under the diagonal")
z = np.diag(X, k=-1)
print(z)

Original
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

Collected
[ 0  6 12 18] 

Above the diagonal
[ 1  7 13 19] 

Under the diagonal
[ 5 11 17]


## Example 6. Demonstrate the unique() function

In [63]:
print("Original")
X = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
print(X, '\n')

print("With unique values")
print(np.unique(X))

Original
[[1 2 3]
 [5 2 8]
 [1 2 3]] 

With unique values
[1 2 3 5 8]
