# Creating Numpy Arrays 2

In [2]:
import numpy as np

## Example 1. Create a Numpy array of zeros with a desired shape

In [3]:
x = np.zeros((3, 4), dtype=int)
print(x)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## Example 2 Create a Numpy array of ones with a desired shape

In [4]:
x = np.ones((4, 5), dtype=int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Example 3. Create a Numpy array of constants

In [13]:
x = np.full((4, 3), 5, dtype=int)

print(x)
print("\nDtype:", x.dtype)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]

Dtype: int64


## Exemple 4.a. Create a Numpy array of an Identity matrix

In [17]:
x = np.eye(5)

print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Exemple 4.b. Create a Numpy array of constants

In [21]:
x = np.diag((10, 20, 30, 50))

print(x)
print("\nDtype:", x.dtype)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]

Dtype: int64


## Example 5. Create a Numpy array of evenly spaced values in a given range, using 

In [36]:
# Case 1: Until reaching the specified argument

x = np.arange(10)

print(x, "\n")

[0 1 2 3 4 5 6 7 8 9] 



## Example 6. Create a Numpy array using arange(start_val, stop_val)

In [35]:
# Case 2: from starter argument to final one

y = np.arange(4, 10)

print(y, "\n")

[4 5 6 7 8 9] 



## Example 7. Create a Numpy array using arange(start_val, stop_val, step_size)

In [34]:
xy = np.arange(1, 14, 3)

print(xy, "\n")

[ 1  4  7 10 13] 



## Example 8. Create a Numpy array using linspace(start, stop, n), with stop inclusive.

In [55]:
print("\n|Example 1|")
x = np.linspace(0, 25, 10)
print(x, "\n")

print("|Example 2|")
x = np.linspace(0, 25, 10, dtype=int)
print(x, "\n")


|Example 1|
[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ] 

|Example 2|
[ 0  2  5  8 11 13 16 19 22 25] 



## Example 9. Create a Numpy array using linspace(start, stop, n), with stop excluded.

In [56]:
x = np.linspace(0, 25, 10, endpoint=False)
print(x, "\n")

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5] 



## Example 10. Create a Numpy array by feeding the output of arange() function as an argument to the reshape() function.

In [52]:
x = np.arange(1, 20 + 1)

x = np.reshape(x, (4, 5))

print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Example 11. Create a Numpy array by calling the reshape() function from the output of arange() function.

In [54]:
x = np.arange(1, 20 + 1).reshape(4,5)

print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Example 12. Create a rank 2 Numpy array by using the reshape() function.

In [66]:
x = np.linspace(0, 50, 10, endpoint=False, dtype=np.float64).reshape(5, 2)

print(x)

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]


## Example 13. Create a Numpy array using the numpy.random.random() function.

In [72]:
x = np.random.random((3, 3))

print(x)

[[0.90413935 0.82675785 0.87248006]
 [0.79543427 0.8934489  0.14684106]
 [0.55480819 0.74701779 0.74603172]]


## Example 14. Create a Numpy array using the numpy.random.randint() function.

In [3]:
x = np.random.randint(3,  15, (3, 2))

print(x)

[[11  7]
 [ 3  9]
 [ 7  7]]


## Example 15. Create a Numpy array of "Normal" distributed random numbers, using the numpy.random.normal() function.

In [69]:
x = np.random.normal(0, 0.1, size=(1000, 1000))

print(x)

[[ 0.01569198 -0.02380714  0.26530344 ...  0.00275869 -0.12832148
  -0.02212853]
 [-0.16827144  0.00103219  0.04388047 ... -0.05905424 -0.11404165
   0.10288564]
 [-0.19154412 -0.14195587  0.09227903 ...  0.07310243  0.16239858
  -0.09223799]
 ...
 [-0.08366482  0.03359927 -0.01370106 ... -0.06024396  0.01853301
  -0.17168303]
 [-0.05814429  0.09877683  0.09263983 ... -0.09844843  0.18743119
  -0.0686262 ]
 [ 0.02294786  0.02845728  0.05412238 ...  0.05376198  0.01819279
   0.03764029]]


In [70]:
print('mean:', x.mean())
print('std:', x.std())
print('max:', x.max())
print('min', x.min())
print('# positive:', (x > 0).sum())
print('# negative', (x < 0).sum())

mean: -9.595343118696381e-05
std: 0.10005174306953388
max: 0.4967140357750719
min -0.49610020749071604
# positive: 500126
# negative 499874
